export { SupabaseApiAssignmentAssessments as SupabaseApiAssignment } from './SupabaseApi.assignment.assessments';
export { SupabaseApiCampaignReports as SupabaseApiCampaign } from './SupabaseApi.campaign.reports';
export { SupabaseApiCoreSync as SupabaseApiCore } from './SupabaseApi.core.sync';
export { SupabaseApiCourseMedia as SupabaseApiCourse } from './SupabaseApi.course.media';
export { SupabaseApiOpsLearningPath as SupabaseApiOps } from './SupabaseApi.ops.learningPath';
export { SupabaseApiPal } from './SupabaseApi.pal';
export { SupabaseApiProgramSchoolStats as SupabaseApiProgram } from './SupabaseApi.program.schoolStats';
export { SupabaseApiRewards } from './SupabaseApi.rewards';
export { SupabaseApiResultsProgress as SupabaseApiResults } from './SupabaseApi.results.progress';
export { SupabaseApiSchoolReferenceData as SupabaseApiSchool } from './SupabaseApi.school.referenceData';
export { SupabaseApiSticker } from './SupabaseApi.sticker';
export { SupabaseApiUserLeaderboards as SupabaseApiUser } from './SupabaseApi.user.leaderboards';
export { SupabaseApiWhatsApp } from './SupabaseApi.whatsapp';
