import { Schema, Table, column } from "@powersync/web";

/**
 * PowerSync schema generated from Supabase types in src/services/database.ts.
 * Keep this in sync with updates to the Supabase schema so client-side
 * syncing stays consistent.
 */
export const PowerSyncSchema = new Schema({
  announcement: new Table({
    created_at: column.text,
    custom_icon: column.text,
    id: column.text,
    image_url: column.text,
    message: column.text,
    send_at: column.text,
    target_ids: column.text,
    title: column.text,
    type: column.text,
  }),
  assignment: new Table({
    batch_id: column.text,
    chapter_id: column.text,
    class_id: column.text,
    course_id: column.text,
    created_at: column.text,
    created_by: column.text,
    ends_at: column.text,
    firebase_id: column.text,
    id: column.text,
    is_class_wise: column.integer,
    is_deleted: column.integer,
    is_firebase: column.integer,
    lesson_id: column.text,
    school_id: column.text,
    source: column.text,
    starts_at: column.text,
    type: column.text,
    updated_at: column.text,
  }),
  assignment_cart: new Table({
    created_at: column.text,
    id: column.text,
    is_deleted: column.integer,
    is_firebase: column.integer,
    lessons: column.text,
    source: column.text,
    updated_at: column.text,
  }),
  assignment_user: new Table({
    assignment_id: column.text,
    created_at: column.text,
    id: column.text,
    is_deleted: column.integer,
    is_firebase: column.integer,
    updated_at: column.text,
    user_id: column.text,
  }),
  auto_chatbot: new Table({
    created_at: column.text,
    id: column.text,
    is_deleted: column.integer,
    school_id: column.text,
    task_data: column.text,
    updated_at: column.text,
  }),
  badge: new Table({
    created_at: column.text,
    description: column.text,
    id: column.text,
    image: column.text,
    is_deleted: column.integer,
    name: column.text,
    updated_at: column.text,
  }),
  chapter: new Table({
    course_id: column.text,
    created_at: column.text,
    id: column.text,
    image: column.text,
    is_deleted: column.integer,
    name: column.text,
    sort_index: column.integer,
    sub_topics: column.text,
    updated_at: column.text,
  }),
  chapter_lesson: new Table({
    chapter_id: column.text,
    created_at: column.text,
    id: column.text,
    is_deleted: column.integer,
    lesson_id: column.text,
    sort_index: column.integer,
    updated_at: column.text,
  }),
  chapter_links: new Table({
    chapter_id: column.text,
    course_id: column.text,
    created_at: column.text,
    curriculum_id: column.text,
    grade_id: column.text,
    id: column.text,
    is_deleted: column.integer,
    link: column.text,
    updated_at: column.text,
  }),
  chatbot: new Table({
    chatbot_doc: column.text,
    created_at: column.text,
    id: column.text,
    is_deleted: column.integer,
    phonenumber: column.text,
    updated_at: column.text,
  }),
  class: new Table({
    academic_year: column.text,
    created_at: column.text,
    firebase_id: column.text,
    group_id: column.text,
    id: column.text,
    image: column.text,
    is_deleted: column.integer,
    is_firebase: column.integer,
    is_ops: column.integer,
    name: column.text,
    ops_created_by: column.text,
    school_id: column.text,
    standard: column.text,
    status: column.text,
    updated_at: column.text,
  }),
  class_course: new Table({
    class_id: column.text,
    course_id: column.text,
    created_at: column.text,
    id: column.text,
    is_deleted: column.integer,
    is_firebase: column.integer,
    is_ops: column.integer,
    ops_created_by: column.text,
    updated_at: column.text,
  }),
  class_invite_code: new Table({
    class_id: column.text,
    code: column.integer,
    created_at: column.text,
    expires_at: column.text,
    id: column.text,
    is_class_code: column.integer,
    is_deleted: column.integer,
    is_firebase: column.integer,
    updated_at: column.text,
  }),
  class_user: new Table({
    class_id: column.text,
    created_at: column.text,
    id: column.text,
    is_deleted: column.integer,
    is_firebase: column.integer,
    is_ops: column.integer,
    ops_created_by: column.text,
    role: column.text,
    updated_at: column.text,
    user_id: column.text,
  }),
  connector_users: new Table({
    created_at: column.text,
    email: column.text,
    id: column.text,
  }),
  course: new Table({
    code: column.text,
    color: column.text,
    created_at: column.text,
    curriculum_id: column.text,
    description: column.text,
    firebase_id: column.text,
    grade_id: column.text,
    id: column.text,
    image: column.text,
    is_deleted: column.integer,
    name: column.text,
    sort_index: column.integer,
    subject_id: column.text,
    updated_at: column.text,
  }),
  curriculum: new Table({
    created_at: column.text,
    description: column.text,
    firebase_id: column.text,
    id: column.text,
    image: column.text,
    is_deleted: column.integer,
    name: column.text,
    sort_index: column.integer,
    updated_at: column.text,
  }),
  error_logs: new Table({
    created_at: column.text,
    id: column.integer,
    message: column.text,
    user_id: column.text,
  }),
  favorite_lesson: new Table({
    created_at: column.text,
    id: column.text,
    is_deleted: column.integer,
    is_firebase: column.integer,
    lesson_id: column.text,
    updated_at: column.text,
    user_id: column.text,
  }),
  geo_locations: new Table({
    block: column.text,
    country: column.text,
    created_at: column.text,
    district: column.text,
    id: column.text,
    is_deleted: column.integer,
    state: column.text,
    updated_at: column.text,
  }),
  grade: new Table({
    created_at: column.text,
    description: column.text,
    firebase_id: column.text,
    id: column.text,
    image: column.text,
    is_deleted: column.integer,
    name: column.text,
    sort_index: column.integer,
    test: column.text,
    updated_at: column.text,
  }),
  issue_debug: new Table({
    created_at: column.text,
    firebase_id: column.text,
    id: column.text,
    is_firebase: column.integer,
    result_id: column.text,
    student_id: column.text,
  }),
  language: new Table({
    code: column.text,
    created_at: column.text,
    description: column.text,
    firebase_id: column.text,
    id: column.text,
    image: column.text,
    is_deleted: column.integer,
    name: column.text,
    sort_index: column.integer,
    updated_at: column.text,
  }),
  lesson: new Table({
    cocos_chapter_code: column.text,
    cocos_lesson_id: column.text,
    cocos_subject_code: column.text,
    color: column.text,
    created_at: column.text,
    created_by: column.text,
    id: column.text,
    image: column.text,
    is_deleted: column.integer,
    language_id: column.text,
    name: column.text,
    outcome: column.text,
    plugin_type: column.text,
    status: column.text,
    subject_id: column.text,
    target_age_from: column.integer,
    target_age_to: column.integer,
    updated_at: column.text,
  }),
  live_quiz_room: new Table({
    assignment_id: column.text,
    class_id: column.text,
    course_id: column.text,
    created_at: column.text,
    id: column.text,
    is_deleted: column.integer,
    lesson_id: column.text,
    participants: column.text,
    results: column.text,
    school_id: column.text,
    starts_at: column.text,
    updated_at: column.text,
  }),
  ops_requests: new Table({
    class_id: column.text,
    created_at: column.text,
    id: column.text,
    is_deleted: column.integer,
    rejected_reason_description: column.text,
    rejected_reason_type: column.text,
    request_ends_at: column.text,
    request_id: column.text,
    request_type: column.text,
    requested_by: column.text,
    requested_to: column.text,
    responded_by: column.text,
    school_id: column.text,
    updated_at: column.text,
  }),
  parent_user: new Table({
    created_at: column.text,
    id: column.text,
    is_deleted: column.integer,
    is_firebase: column.integer,
    is_ops: column.integer,
    ops_created_by: column.text,
    parent_id: column.text,
    student_id: column.text,
    updated_at: column.text,
  }),
  program: new Table({
    block: column.text,
    cluster: column.text,
    country: column.text,
    created_at: column.text,
    devices_count: column.text,
    district: column.text,
    end_date: column.text,
    funding_partner: column.text,
    id: column.text,
    implementation_partner: column.text,
    institute_partner: column.text,
    institutes_count: column.text,
    is_deleted: column.integer,
    is_ops: column.integer,
    model: column.text,
    name: column.text,
    program_type: column.text,
    start_date: column.text,
    state: column.text,
    students_count: column.text,
    updated_at: column.text,
    village: column.text,
  }),
  program_user: new Table({
    created_at: column.text,
    id: column.text,
    is_deleted: column.integer,
    is_ops: column.integer,
    program_id: column.text,
    role: column.text,
    updated_at: column.text,
    user: column.text,
  }),
  req_new_school: new Table({
    city: column.text,
    created_at: column.text,
    district: column.text,
    id: column.text,
    image: column.text,
    is_deleted: column.integer,
    is_resolved: column.integer,
    name: column.text,
    state: column.text,
    udise_id: column.text,
    updated_at: column.text,
    user_id: column.text,
  }),
  result: new Table({
    assignment_id: column.text,
    chapter_id: column.text,
    class_id: column.text,
    correct_moves: column.integer,
    course_id: column.text,
    created_at: column.text,
    firebase_id: column.text,
    id: column.text,
    is_deleted: column.integer,
    is_firebase: column.integer,
    lesson_id: column.text,
    school_id: column.text,
    score: column.integer,
    student_id: column.text,
    time_spent: column.integer,
    updated_at: column.text,
    wrong_moves: column.integer,
  }),
  reward: new Table({
    created_at: column.text,
    id: column.text,
    is_deleted: column.integer,
    monthly: column.text,
    updated_at: column.text,
    weekly: column.text,
    weeklySticker: column.text,
    year: column.integer,
  }),
  rive_reward: new Table({
    accessory_name: column.text,
    animation_name: column.text,
    created_at: column.text,
    id: column.text,
    is_deleted: column.integer,
    max_state_value: column.integer,
    state_input_name: column.text,
    state_machine: column.text,
    state_number_input: column.integer,
    type: column.text,
    updated_at: column.text,
  }),
  saved_queries: new Table({
    created_at: column.text,
    id: column.text,
    query: column.text,
  }),
  school: new Table({
    academic_year: column.text,
    address: column.text,
    country: column.text,
    created_at: column.text,
    firebase_id: column.text,
    group1: column.text,
    group2: column.text,
    group3: column.text,
    group4: column.text,
    id: column.text,
    image: column.text,
    is_deleted: column.integer,
    is_firebase: column.integer,
    is_ops: column.integer,
    key_contacts: column.text,
    language: column.text,
    model: column.text,
    name: column.text,
    ops_created_by: column.text,
    program_id: column.text,
    status: column.text,
    student_login_type: column.text,
    udise: column.text,
    updated_at: column.text,
  }),
  school_course: new Table({
    course_id: column.text,
    created_at: column.text,
    id: column.text,
    is_deleted: column.integer,
    is_firebase: column.integer,
    is_ops: column.integer,
    ops_created_by: column.text,
    school_id: column.text,
    updated_at: column.text,
  }),
  school_data: new Table({
    block: column.text,
    classes: column.text,
    cluster: column.text,
    country: column.text,
    created_at: column.text,
    district: column.text,
    head_teacher: column.text,
    head_teachers: column.text,
    id: column.text,
    instruction_medium: column.text,
    pre_primary_section_available: column.integer,
    school_name: column.text,
    school_type: column.text,
    state: column.text,
    total_teachers: column.integer,
    udise_code: column.text,
    updated_at: column.text,
    village: column.text,
  }),
  school_user: new Table({
    created_at: column.text,
    id: column.text,
    is_deleted: column.integer,
    is_firebase: column.integer,
    is_ops: column.integer,
    ops_created_by: column.text,
    role: column.text,
    school_id: column.text,
    updated_at: column.text,
    user_id: column.text,
  }),
  special_users: new Table({
    created_at: column.text,
    id: column.text,
    is_deleted: column.integer,
    role: column.text,
    updated_at: column.text,
    user_id: column.text,
  }),
  sticker: new Table({
    created_at: column.text,
    description: column.text,
    id: column.text,
    image: column.text,
    is_deleted: column.integer,
    name: column.text,
    updated_at: column.text,
  }),
  subject: new Table({
    created_at: column.text,
    description: column.text,
    id: column.text,
    image: column.text,
    is_deleted: column.integer,
    name: column.text,
    sort_index: column.integer,
    updated_at: column.text,
  }),
  upload_queue: new Table({
    batch_number: column.integer,
    created_at: column.text,
    error: column.text,
    id: column.text,
    is_locked: column.integer,
    locked_at: column.text,
    locked_by: column.text,
    locked_until: column.text,
    payload: column.text,
    process_started_at: column.text,
    start_time: column.text,
    status: column.text,
    updated_at: column.text,
    uploading_user: column.text,
  }),
  user: new Table({
    age: column.integer,
    avatar: column.text,
    created_at: column.text,
    curriculum_id: column.text,
    email: column.text,
    fcm_token: column.text,
    firebase_id: column.text,
    gender: column.text,
    grade_id: column.text,
    id: column.text,
    image: column.text,
    is_deleted: column.integer,
    is_firebase: column.integer,
    is_ops: column.integer,
    is_tc_accepted: column.integer,
    language_id: column.text,
    learning_path: column.text,
    music_off: column.integer,
    name: column.text,
    ops_created_by: column.text,
    phone: column.text,
    reward: column.text,
    sfx_off: column.integer,
    stars: column.integer,
    student_id: column.text,
    updated_at: column.text,
  }),
  user_badge: new Table({
    badge_id: column.text,
    created_at: column.text,
    id: column.text,
    is_deleted: column.integer,
    is_firebase: column.integer,
    is_seen: column.integer,
    updated_at: column.text,
    user_id: column.text,
  }),
  user_bonus: new Table({
    bonus_id: column.text,
    created_at: column.text,
    id: column.text,
    is_deleted: column.integer,
    is_firebase: column.integer,
    is_seen: column.integer,
    updated_at: column.text,
    user_id: column.text,
  }),
  user_course: new Table({
    course_id: column.text,
    created_at: column.text,
    id: column.text,
    is_deleted: column.integer,
    is_firebase: column.integer,
    updated_at: column.text,
    user_id: column.text,
  }),
  user_sticker: new Table({
    created_at: column.text,
    id: column.text,
    is_deleted: column.integer,
    is_firebase: column.integer,
    is_seen: column.integer,
    sticker_id: column.text,
    updated_at: column.text,
    user_id: column.text,
  }),
});
