import { GrowthBookAttributesPayload } from './background.worker.types';

export const buildGrowthBookAttributes = (
  payload: GrowthBookAttributesPayload,
) => {
  const attributes = payload.attributes ?? {};
  const {
    studentDetails,
    schools,
    school_name,
    classes,
    liveQuizCount = 0,
    assignmentCount = 0,
    last_assignment_played_at,
    total_assignments_played = 0,
    leaderboard_position_weekly = 0,
    leaderboard_position_monthly = 0,
    leaderboard_position_all = 0,
    count_of_assignment_played = 0,
    count_of_lessons_played = 0,
    pending_course_counts = {},
    pending_subject_counts = {},
    learning_path_completed = {},
    total_learning_path_completed = 0,
    manufacturer,
    model,
    operating_system,
    os_version,
    platform,
    device_language,
    count_of_children = 0,
    teacher_class_id,
    teacher_school_state,
    teacher_school_district,
    teacher_school_block,
    teacher_school_id,
    teacher_school_list,
    teacher_class_ids,
    roleMap = {},
    courseCounts = {},
  } = attributes;

  const totalAssignments = count_of_assignment_played + assignmentCount;
  const percentageOfAssignmentPlayed =
    totalAssignments > 0
      ? (count_of_assignment_played / totalAssignments) * 100
      : 0;

  return {
    id: studentDetails?.id,
    age: studentDetails?.age,
    curriculum_id: studentDetails?.curriculum_id,
    grade_id: studentDetails?.grade_id,
    gender: studentDetails?.gender,
    parent_id: studentDetails?.parent_id,
    student_id: studentDetails?.id,
    subject_id: studentDetails?.subject_id,
    stars: studentDetails?.stars || 0,
    last_login_at: studentDetails?.last_sign_in_at,
    login_method: studentDetails?.login_method,
    school_ids: schools,
    school_name,
    class_ids: classes,
    language: payload.language || 'en',
    pending_live_quiz: liveQuizCount,
    pending_assignments: assignmentCount,
    last_assignment_played_at,
    total_assignments_played,
    leaderboard_position_weekly,
    leaderboard_position_monthly,
    leaderboard_position_all,
    count_of_assignment_played,
    count_of_lessons_played,
    percentage_of_assignment_played: percentageOfAssignmentPlayed,
    ...pending_course_counts,
    ...pending_subject_counts,
    ...learning_path_completed,
    total_learning_path_completed,
    manufacturer,
    model,
    operating_system,
    os_version,
    platform,
    device_language,
    count_of_children,
    teacher_class_id,
    teacher_school_id,
    teacher_school_state,
    teacher_school_district,
    teacher_school_block,
    teacher_school_list,
    teacher_class_ids,
    ...roleMap,
    ...courseCounts,
  };
};
