//@ts-nocheck
import type { Meta, StoryObj } from "@storybook/react";
import StudentReportHeader from "../../components/studentReport/StudentReportHeader";

const meta = {
  title: "teachers-module/studentReport/StudentReportHeader",
  component: StudentReportHeader,
  tags: ["autodocs"],
  argTypes: {},

  args: {},
} satisfies Meta<typeof StudentReportHeader>;
export default meta;
type Story = StoryObj<typeof meta>;
export const Test2: Story = {
  args: {
    student: {
      age: 10,
      avatar: "chefrat",
      created_at: "20-07-2024",
      curriculum_id: "curriculum_id",
      email: "",
      fcm_token: "",
      gender: "male",
      grade_id: "grade_id",
      id: "string",
      image: "image",
      is_deleted: false,
      is_tc_accepted: false,
      language_id: "language_id",
      music_off: false,
      name: "chimple",
      phone: "",
      sfx_off: true,
      student_id: "student_id",
      updated_at: "20-07-2024",
      firebase_id: null,
      is_firebase: null,
      is_ops: null,
      learning_path: null,
      ops_created_by: null,
      stars: null,
      reward: null
    },
    mappedSubjectOptions: [{ id: "a", name: "Digital", icon: "/assets/icons/DefaultIcon.png", subjectDetail: "Digital Skills - Grade 4", }],
    onSubjectChange: () => {},
    currentClass: {
      created_at: "20-07-2024",
      id: "class",
      image: "",
      is_deleted: false,
      name: "chimple",
      school_id: "school_id",
      updated_at: "20-07-2024",
      academic_year: null,
      firebase_id: null,
      is_firebase: null,
      is_ops: null,
      ops_created_by: null,
      standard: null,
      status: null,
      group_id: null
    },
    selectedSubject: {
      code: "en",
      color: "red",
      created_at: "20-07-2024",
      curriculum_id: "curriculum_id",
      description: "Description",
      grade_id: "grade_id",
      id: "subject_id",
      image: "image",
      is_deleted: false,
      name: "string",
      sort_index: 1,
      subject_id: "subject_id",
      updated_at: "20-07-2024",
      firebase_id: null
    },
  },
};
export const Test3: Story = {
  args: {
    student: {
      age: 10,
      avatar: "chefrat",
      created_at: "20-07-2024",
      curriculum_id: "curriculum_id",
      email: "",
      fcm_token: "",
      gender: "male",
      grade_id: "grade_id",
      id: "string",
      image: "image",
      is_deleted: false,
      is_tc_accepted: false,
      language_id: "language_id",
      music_off: false,
      name: "Vidya",
      phone: "",
      sfx_off: true,
      student_id: "student_id",
      updated_at: "20-07-2024",
      firebase_id: null,
      is_firebase: null,
      is_ops: null,
      learning_path: null,
      ops_created_by: null,
      stars: null,
      reward: null
    },
    mappedSubjectOptions: [
  {
    id: "a",
    name: "Digital Skills",
    icon: "/assets/icons/DefaultIcon.png",
    subjectDetail: "Digital Skills - Grade 4",
  },
  {
    id: "b",
    name: "Maths",
    icon: "/assets/icons/DefaultIcon.png",
    subjectDetail: "Maths - Grade 5",
  },
  {
    id: "c",
    name: "English",
    icon: "/assets/icons/DefaultIcon.png",
    subjectDetail: "English - Grade 6",
  },
],
    onSubjectChange: () => {},
    currentClass: {
      created_at: "20-07-2024",
      id: "class",
      image: "",
      is_deleted: false,
      name: "chimple",
      school_id: "school_id",
      updated_at: "20-07-2024",
      academic_year: null,
      firebase_id: null,
      is_firebase: null,
      is_ops: null,
      ops_created_by: null,
      standard: null,
      status: null,
      group_id: null
    },
    selectedSubject: {
      code: "en",
      color: "red",
      created_at: "20-07-2024",
      curriculum_id: "curriculum_id",
      description: "Description",
      grade_id: "grade_id",
      id: "subject_id",
      image: "image",
      is_deleted: false,
      name: "string",
      sort_index: 1,
      subject_id: "subject_id",
      updated_at: "20-07-2024",
      firebase_id: null
    },
  },
};
export const Test4: Story = {
  args: {
    student: {
      age: 10,
      avatar: "chefrat",
      created_at: "20-07-2024",
      curriculum_id: "curriculum_id",
      email: "",
      fcm_token: "",
      gender: "male",
      grade_id: "grade_id",
      id: "string",
      image: "image",
      is_deleted: false,
      is_tc_accepted: false,
      language_id: "language_id",
      music_off: false,
      name: "Kumar",
      phone: "",
      sfx_off: true,
      student_id: "student_id",
      updated_at: "20-07-2024",
      firebase_id: null,
      is_firebase: null,
      is_ops: null,
      learning_path: null,
      ops_created_by: null,
      reward: null,
      stars: null
    },
    mappedSubjectOptions: [{ id: "a", name: "Digital Skills",icon: "/assets/icons/DefaultIcon.png" ,subjectDetail: "Digital Skills - Grade 4", },{ id: "a", name: "Kannada", icon: "/assets/icons/DefaultIcon.png", subjectDetail: "Kannada - Grade 5" }],
    onSubjectChange: () => {},
    currentClass: {
      created_at: "20-07-2024",
      id: "class",
      image: "",
      is_deleted: false,
      name: "chimple",
      school_id: "school_id",
      updated_at: "20-07-2024",
      academic_year: null,
      firebase_id: null,
      is_firebase: null,
      is_ops: null,
      ops_created_by: null,
      standard: null,
      status: null,
      group_id: null
    },
    selectedSubject: {
      code: "en",
      color: "red",
      created_at: "20-07-2024",
      curriculum_id: "curriculum_id",
      description: "Description",
      grade_id: "grade_id",
      id: "subject_id",
      image: "image",
      is_deleted: false,
      name: "string",
      sort_index: 1,
      subject_id: "subject_id",
      updated_at: "20-07-2024",
      firebase_id: null
    },
  },
};
