name: Build Android

on:
  push:
    branches:
      - beta

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: "17"

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Install app dependencies
        run: npm install

      - name: Create Google Services JSON File and key.jks
        working-directory: ./android/app/
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON_PROD }}
          SHA_KEY: ${{ secrets.SHA_KEY_PROD }}
        run: |
          echo $GOOGLE_SERVICES_JSON | base64 -di > google-services.json
          echo $SHA_KEY | base64 -di > key.jks

      - name: Build
        env:
          CI: false
          REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY_PROD }}
          REACT_APP_AUTH_DOMAIN: ${{ secrets.REACT_APP_AUTH_DOMAIN_PROD }}
          REACT_APP_PROJECT_ID: ${{ secrets.REACT_APP_PROJECT_ID_PROD }}
          REACT_APP_STORAGE_BUCKET: ${{ secrets.REACT_APP_STORAGE_BUCKET_PROD }}
          REACT_APP_MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_MESSAGING_SENDER_ID_PROD }}
          REACT_APP_APP_ID: ${{ secrets.REACT_APP_APP_ID_PROD }}
          REACT_APP_MEASUREMENT_ID: ${{ secrets.REACT_APP_MEASUREMENT_ID_PROD}}
          REACT_APP_ALGOLIA_APP_ID: ${{ secrets.REACT_APP_ALGOLIA_APP_ID }}
          REACT_APP_ALGOLIA_API_KEY: ${{ secrets.REACT_APP_ALGOLIA_API_KEY }}
          REACT_APP_HOT_UPDATE_SERVER: ${{ secrets.BETA_HOT_UPDATE_SERVER }}
          REACT_APP_ALGOLIA_INDEX_NAME: ${{ secrets.REACT_APP_ALGOLIA_INDEX_NAME_PROD}}
          REACT_APP_RAPIDAPI_KEY: ${{ secrets.REACT_APP_RAPIDAPI_KEY }}

        run: npm run build

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v13.0.3
        with:
          args: deploy --only hosting:chimple-prod-hot-update-beta
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Make gradlew executable
        working-directory: ./android/
        run: chmod +x ./gradlew

      - name: Generate the Android App bundleRelease
        working-directory: ./android/
        # android/app/build/outputs/bundle/release/app-release.aab
        run: ./gradlew bundleRelease

      - name: Generate the Android App apk
        working-directory: ./android/
        # android/app/build/outputs/apk/release/app-release.apk
        run: ./gradlew assembleRelease

      - name: Generate the Android App assembleDebug
        working-directory: ./android/
        run: ./gradlew assembleDebug

      - name: Deploy apk
        working-directory: .
        run: |
          cd android/app/build/outputs/
          git init
          git config --global user.email prakash@sutara.org
          git config --global user.name  bhanugummana
          git remote add origin https://${{ secrets.ACCESS_TOKEN }}@github.com/chimple/cuba.git
          git checkout -b apk-beta
          # git add app-debug.apk
          git add bundle/release/app-release.aab
          git add apk/release/app-release.apk
          git add apk/debug/app-debug.apk
          git commit -m "created beta apk"
          git push origin apk-beta -f

      # - name: Pushes to Hot update
      #   uses: cpina/github-action-push-to-another-repository@main
      #   env:
      #     API_TOKEN_GITHUB: ${{ secrets.ACCESS_TOKEN }}
      #   with:
      #     source-directory: "build"
      #     target-directory: "public/v1"
      #     destination-github-username: "chimple"
      #     destination-repository-name: "cuba-hot-update"
      #     user-email: prakash@sutara.org
      #     target-branch: main
